### ISSUE TITLE
Read timeout is to low

### ISSUE THREAD

**Issue by pchris7489** [mluis7/xml2xpath#11]
Hello,

In the functions `parse_ns_from_xpath` and `print_response`

The part  `while read -r -u 3 -t 5 xline`, the timeout is to low. If there is an antivirus or a slow computer, it will timeout everytime. 

It is should possible to customise the timeout, for example :

`local timelimit=30 ; 
[ -n "$timelimit" ] && timelimit=$1; 
while read -r -u 3 -t $timelimit xline`

Where timelimit would be an argument

**Comment by mluis7** [comment]
@pchris7489 
it could be possible to customize the timeout using an env variable. Will see what I can do.
Thanks for taking the time to read the code and suggest a fix.
