### ISSUE TITLE
Not working on Termux

### ISSUE THREAD

**Issue by pchris7489** [mluis7/xml2xpath#12]
Hello,

I am trying to make this run on Termux (Android, Google Pixel 8), but I am facing timeout 142 issues.

I think the problem comes from the line

`while IFS=$'\n' read -r -u 3 -t 30 xline || is_read_error "$?" "$2"; do`

I cant manage to rewrite it to prevent the timeout

**Comment by mluis7** [comment]
@pchris7489 
It didn't work even with `-t 30`?
I haven`t tested on Android. Could you please add which shell it uses including the version?
